language: bash
dist: xenial
os: linux

sudo: enabled
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: yes
    - PATH: "/snap/bin:$PATH"

addons:
  snaps:
    - name: core
    - name: snapcraft
      classic: true
    - name: lxd
    - name: http
    - name: transfer
before_script:
  - sudo apt autoremove --purge lxd lxd-client
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
script:
  - sudo snapcraft --use-lxd
  - sudo cp *.snap "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_success:
  - timeout 180 sudo /snap/bin/transfer "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_failure:
  - sudo journalctl -u snapd
  - /snap/bin/http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
