name: eclipse
version: '4.7.3a'
summary: Extensible Tool Platform and Java IDE
description:
  Eclipse provides IDEs and platforms for nearly every language and architecture.
  We are famous for our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible
  platforms for creating desktop, Web and cloud IDEs. These platforms deliver the most
  extensive collection of add-on tools available for software developers.
grade: stable
confinement: classic
architectures:
  - amd64
  
apps:
  eclipse:
    command: eclipse
    desktop: eclipse.desktop

parts:
  desktop:
    after: [eclipse]
    plugin: dump
    source: .
    prime:
      - eclipse.desktop
  eclipse:
    plugin: dump
    source: http://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/downloads/release/oxygen/3a/eclipse-java-oxygen-3a-linux-gtk-x86_64.tar.gz
    build-attributes:
      - no-patchelf
